### ISSUE TITLE
About in running

### ISSUE THREAD

**Issue by xixiaxsssd** [WisconsinAIVision/UniversalFakeDetect#14]
Length of dataset: 0
Traceback (most recent call last):
  File "/content/UniversalFakeDetect/train.py", line 70, in <module>
    ap, r_acc, f_acc, acc = validate(model.model, val_loader)
  File "/content/UniversalFakeDetect/validate.py", line 116, in validate
    ap = average_precision_score(y_true, y_pred)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_ranking.py", line 234, in average_precision_score
    return _average_binary_score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_ranking.py", line 207, in _binary_uninterpolated_average_precision
    precision, recall, _ = precision_recall_curve(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_ranking.py", line 878, in precision_recall_curve
    fps, tps, thresholds = _binary_clf_curve(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_ranking.py", line 787, in _binary_clf_curve
    tps = stable_cumsum(y_true * weight)[threshold_idxs]
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/extmath.py", line 1142, in stable_cumsum
    out.take(-1, axis=axis), expected, rtol=rtol, atol=atol, equal_nan=True
IndexError: cannot do a non-empty take from an empty axes.

How can i fix it?Is my dataset causing that error?

**Comment by SleeplessBegonia** [comment]
me 2.how did u solve it?

**Comment by YuZehanghhh** [comment]
> me 2.how did u solve it?
same issue, did u solve it?

**Comment by 1989XiaoXin** [comment]
Hi,try to modify dataset_paths.py

**Comment by wenxian-ok** [comment]
> Hi,try to modify dataset_paths.py

How did you modify it? I also encountered this problem! Translate into English

**Comment by wenxian-ok** [comment]
> Hi,try to modify dataset_paths.py

How did you modify it? I also encountered this problem!

**Comment by freely000** [comment]
I also encountered this issuse, how to solve it, please?

**Comment by SleeplessBegonia** [comment]
> I also encountered this issuse, how to solve it, please?

https://github.com/WisconsinAIVision/UniversalFakeDetect/issues/14#issuecomment-2235985375

**Comment by freely000** [comment]
> > I also encountered this issuse, how to solve it, please?
> 
> [#14 (comment)](https://github.com/WisconsinAIVision/UniversalFakeDetect/issues/14#issuecomment-2235985375)

It's useful. Thank you very much!

**Comment by hjs-2002** [comment]
help

**Comment by gonhjj** [comment]
修改dataset_paths.py。
如果指定路径用python validate.py  --arch=CLIP:ViT-L/14   --ckpt=pretrained_weights/fc_weights.pth   --res
ult_folder=clip_vitl14  --real_path datasets/test/progan/0_real --fake_path datasets/test/progan/1_fake --data_mode wang2020
测试。
需要在validate.py中添加parser.add_argument('--key', type=str, default='progan')和修改dataset_paths = [ dict(real_path=opt.real_path, fake_path=opt.fake_path, data_mode=opt.data_mode, key=opt.key) ]。
如果我的回答有错误，希望指正。
